import { CardModel } from '../models/card-model';

export const mockedCards: Map<string, CardModel[]> = new Map([
  [
    'action-a',
    [
      {
        name: 'cry',
        image: '../images/action-a/cry.jpg',
        audio: '../audio/action-a/cry.mp3',
        title: 'Cry',
        translation: 'Плакать',
      },
      {
        name: 'dance',
        image: '../images/action-a/dance.jpg',
        audio: '../audio/action-a/dance.mp3',
        title: 'Dance',
        translation: 'Танцевать',
      },
      {
        name: 'dive',
        image: '../images/action-a/dive.jpg',
        audio: '../audio/action-a/dive.mp3',
        title: 'Dive',
        translation: 'Нырять',
      },
      {
        name: 'draw',
        image: '../images/action-a/draw.jpg',
        audio: '../audio/action-a/draw.mp3',
        title: 'Draw',
        translation: 'Рисовать',
      },
      {
        name: 'fish',
        image: '../images/action-a/fish.jpg',
        audio: '../audio/action-a/fish.mp3',
        title: 'Fish',
        translation: 'Ловить рыбу',
      },
      {
        name: 'hug',
        image: '../images/action-a/hug.jpg',
        audio: '../audio/action-a/hug.mp3',
        title: 'Hug',
        translation: 'Обнимать',
      },
      {
        name: 'jump',
        image: '../images/action-a/jump.jpg',
        audio: '../audio/action-a/jump.mp3',
        title: 'Jump',
        translation: 'Прыгать',
      },
      {
        name: 'open',
        image: '../images/action-a/open.jpg',
        audio: '../audio/action-a/open.mp3',
        title: 'Open',
        translation: 'Открывать',
      },
    ],
  ],
  [
    'action-b',
    [
      {
        name: 'fly',
        image: '../images/action-b/fly.jpg',
        audio: '../audio/action-b/fly.mp3',
        title: 'Fly',
        translation: 'Летать',
      },
      {
        name: 'play',
        image: '../images/action-b/play.jpg',
        audio: '../audio/action-b/play.mp3',
        title: 'Play',
        translation: 'Играть',
      },
      {
        name: 'point',
        image: '../images/action-b/point.jpg',
        audio: '../audio/action-b/point.mp3',
        title: 'Point',
        translation: 'Указывать',
      },
      {
        name: 'ride',
        image: '../images/action-b/ride.jpg',
        audio: '../audio/action-b/ride.mp3',
        title: 'Ride',
        translation: 'Ездить',
      },
      {
        name: 'run',
        image: '../images/action-b/run.jpg',
        audio: '../audio/action-b/run.mp3',
        title: 'Run',
        translation: 'Бегать',
      },
      {
        name: 'skip',
        image: '../images/action-b/skip.jpg',
        audio: '../audio/action-b/skip.mp3',
        title: 'Skip',
        translation: 'Пропускать, прыгать',
      },
      {
        name: 'sing',
        image: '../images/action-b/sing.jpg',
        audio: '../audio/action-b/sing.mp3',
        title: 'Sing',
        translation: 'Петь',
      },
      {
        name: 'swim',
        image: '../images/action-b/swim.jpg',
        audio: '../audio/action-b/swim.mp3',
        title: 'Swim',
        translation: 'Плавать',
      },
    ],
  ],
  [
    'animal-a',
    [
      {
        name: 'bird',
        image: '../images/animal-a/bird.jpg',
        audio: '../audio/animal-a/bird.mp3',
        title: 'Bird',
        translation: 'Птица',
      },
      {
        name: 'cat',
        image: '../images/animal-a/cat.jpg',
        audio: '../audio/animal-a/cat.mp3',
        title: 'Cat',
        translation: 'Кот',
      },
      {
        name: 'chick',
        image: '../images/animal-a/chick.jpg',
        audio: '../audio/animal-a/chick.mp3',
        title: 'Chick',
        translation: 'Цыплёнок',
      },
      {
        name: 'dog',
        image: '../images/animal-a/dog.jpg',
        audio: '../audio/animal-a/dog.mp3',
        title: 'Dog',
        translation: 'Собака',
      },
      {
        name: 'dolphin',
        image: '../images/animal-a/dolphin.jpg',
        audio: '../audio/animal-a/dolphin.mp3',
        title: 'Dolphin',
        translation: 'Дельфин',
      },
      {
        name: 'fish',
        image: '../images/animal-a/fish.jpg',
        audio: '../audio/animal-a/fish.mp3',
        title: 'Fish',
        translation: 'Рыба',
      },
      {
        name: 'frog',
        image: '../images/animal-a/frog.jpg',
        audio: '../audio/animal-a/frog.mp3',
        title: 'Frog',
        translation: 'Лягушка',
      },
      {
        name: 'giraffe',
        image: '../images/animal-a/giraffe.jpg',
        audio: '../audio/animal-a/giraffe.mp3',
        title: 'Giraffe',
        translation: 'Жираф',
      },
    ],
  ],
  [
    'animal-b',
    [
      {
        name: 'chicken',
        image: '../images/animal-b/chicken.jpg',
        audio: '../audio/animal-b/chicken.mp3',
        title: 'Chicken',
        translation: 'Курица',
      },
      {
        name: 'horse',
        image: '../images/animal-b/horse.jpg',
        audio: '../audio/animal-b/horse.mp3',
        title: 'Horse',
        translation: 'Лошадь',
      },
      {
        name: 'lion',
        image: '../images/animal-b/lion.jpg',
        audio: '../audio/animal-b/lion.mp3',
        title: 'Lion',
        translation: 'Лев',
      },
      {
        name: 'mouse',
        image: '../images/animal-b/mouse.jpg',
        audio: '../audio/animal-b/mouse.mp3',
        title: 'Mouse',
        translation: 'Мышь',
      },
      {
        name: 'pig',
        image: '../images/animal-b/pig.jpg',
        audio: '../audio/animal-b/pig.mp3',
        title: 'pig',
        translation: 'Свинья',
      },
      {
        name: 'rabbit',
        image: '../images/animal-b/rabbit.jpg',
        audio: '../audio/animal-b/rabbit.mp3',
        title: 'Rabbit',
        translation: 'Кролик',
      },
      {
        name: 'sheep',
        image: '../images/animal-b/sheep.jpg',
        audio: '../audio/animal-b/sheep.mp3',
        title: 'Sheep',
        translation: 'Овца',
      },
      {
        name: 'turtle',
        image: '../images/animal-b/turtle.jpg',
        audio: '../audio/animal-b/turtle.mp3',
        title: 'Turtle',
        translation: 'Черепаха',
      },
    ],
  ],
  [
    'animal-c',
    [
      {
        name: 'antelope',
        image: '../images/animal-c/antelope.jpg',
        audio: '../audio/animal-c/antelope.mp3',
        title: 'Antelope',
        translation: 'Антилопа',
      },
      {
        name: 'bear',
        image: '../images/animal-c/bear.jpg',
        audio: '../audio/animal-c/bear.mp3',
        title: 'Bear',
        translation: 'Медведь',
      },
      {
        name: 'buffalo',
        image: '../images/animal-c/buffalo.jpg',
        audio: '../audio/animal-c/buffalo.mp3',
        title: 'Buffalo',
        translation: 'Буйвол',
      },
      {
        name: 'cow',
        image: '../images/animal-c/cow.jpg',
        audio: '../audio/animal-c/cow.mp3',
        title: 'Cow',
        translation: 'Корова',
      },
      {
        name: 'flamingo',
        image: '../images/animal-c/flamingo.jpg',
        audio: '../audio/animal-c/flamingo.mp3',
        title: 'Flamingo',
        translation: 'Фламинго',
      },
      {
        name: 'fox',
        image: '../images/animal-c/fox.jpg',
        audio: '../audio/animal-c/fox.mp3',
        title: 'Fox',
        translation: 'Лиса',
      },
      {
        name: 'hedgehog',
        image: '../images/animal-c/hedgehog.jpg',
        audio: '../audio/animal-c/hedgehog.mp3',
        title: 'Hedgehog',
        translation: 'Ёж',
      },
      {
        name: 'squirrel',
        image: '../images/animal-c/squirrel.jpg',
        audio: '../audio/animal-c/squirrel.mp3',
        title: 'Squirrel',
        translation: 'Белка',
      },
    ],
  ],
  [
    'clothes',
    [
      {
        name: 'blouse',
        image: '../images/clothes/blouse.jpg',
        audio: '../audio/clothes/blouse.mp3',
        title: 'Blouse',
        translation: 'Блузка',
      },
      {
        name: 'boot',
        image: '../images/clothes/boot.jpg',
        audio: '../audio/clothes/boot.mp3',
        title: 'Boot',
        translation: 'Ботинок',
      },
      {
        name: 'coat',
        image: '../images/clothes/coat.jpg',
        audio: '../audio/clothes/coat.mp3',
        title: 'Coat',
        translation: 'Пальто',
      },
      {
        name: 'dress',
        image: '../images/clothes/dress.jpg',
        audio: '../audio/clothes/dress.mp3',
        title: 'Dress',
        translation: 'Платье',
      },
      {
        name: 'pants',
        image: '../images/clothes/pants.jpg',
        audio: '../audio/clothes/pants.mp3',
        title: 'Pants',
        translation: 'Брюки',
      },
      {
        name: 'shirt',
        image: '../images/clothes/shirt.jpg',
        audio: '../audio/clothes/shirt.mp3',
        title: 'Shirt',
        translation: 'Рубашка',
      },
      {
        name: 'shoe',
        image: '../images/clothes/shoe.jpg',
        audio: '../audio/clothes/shoe.mp3',
        title: 'Shoe',
        translation: 'Туфли',
      },
      {
        name: 'skirt',
        image: '../images/clothes/skirt.jpg',
        audio: '../audio/clothes/skirt.mp3',
        title: 'Skirt',
        translation: 'Юбка',
      },
    ],
  ],
  [
    'emotions',
    [
      {
        name: 'angry',
        image: '../images/emotions/angry.jpg',
        audio: '../audio/emotions/angry.mp3',
        title: 'Angry',
        translation: 'Сердитый',
      },
      {
        name: 'happy',
        image: '../images/emotions/happy.jpg',
        audio: '../audio/emotions/happy.mp3',
        title: 'Happy',
        translation: 'Счастливый',
      },
      {
        name: 'laugh',
        image: '../images/emotions/laugh.jpg',
        audio: '../audio/emotions/laugh.mp3',
        title: 'Laugh',
        translation: 'Смех',
      },
      {
        name: 'sad',
        image: '../images/emotions/sad.jpg',
        audio: '../audio/emotions/sad.mp3',
        title: 'Sad',
        translation: 'Грустный',
      },
      {
        name: 'scared',
        image: '../images/emotions/scared.jpg',
        audio: '../audio/emotions/scared.mp3',
        title: 'Scared',
        translation: 'Испуганный',
      },
      {
        name: 'smile',
        image: '../images/emotions/smile.jpg',
        audio: '../audio/emotions/smile.mp3',
        title: 'Smile',
        translation: 'Улыбка',
      },
      {
        name: 'surprised',
        image: '../images/emotions/surprised.jpg',
        audio: '../audio/emotions/surprised.mp3',
        title: 'Surprised',
        translation: 'Удивлённый',
      },
      {
        name: 'tired',
        image: '../images/emotions/tired.jpg',
        audio: '../audio/emotions/tired.mp3',
        title: 'Tired',
        translation: 'Уставший',
      },
    ],
  ],
  [
    'food',
    [
      {
        name: 'carrot',
        image: '../images/food/carrot.jpg',
        audio: '../audio/food/carrot.mp3',
        title: 'Carrot',
        translation: 'Морковь',
      },
      {
        name: 'donut',
        image: '../images/food/donut.jpg',
        audio: '../audio/food/donut.mp3',
        title: 'Donut',
        translation: 'Пончик',
      },
      {
        name: 'pear',
        image: '../images/food/pear.jpg',
        audio: '../audio/food/pear.mp3',
        title: 'Pear',
        translation: 'Груша',
      },
      {
        name: 'pizza',
        image: '../images/food/pizza.jpg',
        audio: '../audio/food/pizza.mp3',
        title: 'Pizza',
        translation: 'Пицца',
      },
      {
        name: 'radish',
        image: '../images/food/radish.jpg',
        audio: '../audio/food/radish.mp3',
        title: 'Radish',
        translation: 'Редис',
      },
      {
        name: 'strawberry',
        image: '../images/food/strawberry.jpg',
        audio: '../audio/food/strawberry.mp3',
        title: 'Strawberry',
        translation: 'Клубника',
      },
      {
        name: 'tomatoes',
        image: '../images/food/tomatoes.jpg',
        audio: '../audio/food/tomatoes.mp3',
        title: 'Tomatoes',
        translation: 'Помидоры',
      },
      {
        name: 'watermelon',
        image: '../images/food/watermelon.jpg',
        audio: '../audio/food/watermelon.mp3',
        title: 'Watermelon',
        translation: 'Арбуз',
      },
    ],
  ],
]);
