import { config } from '../config';
import { CreateCardDto } from '../dto/create-card';
import { CardRepository } from '../interfaces/card-repository';
import { Card } from '../models/card';

export class MemoryCardRepository implements CardRepository {
  private cards: Card[] = [
    // Animals set A #0
    new Card(
      'bird',
      'Bird',
      `${config.host}/public/static/images/animal-a/bird.jpg`,
      `${config.host}/public/static/audio/animal-a/bird.mp3`,
      'Птица',
      'cat0',
      '0',
    ),
    new Card(
      'cat',
      'Cat',
      `${config.host}/public/static/images/animal-a/cat.jpg`,
      `${config.host}/public/static/audio/animal-a/cat.mp3`,
      'Кот',
      'cat0',
      '1',
    ),
    new Card(
      'chick',
      'Chick',
      `${config.host}/public/static/images/animal-a/chick.jpg`,
      `${config.host}/public/static/audio/animal-a/chick.mp3`,
      'Цыплёнок',
      'cat0',
      '2',
    ),
    new Card(
      'dog',
      'Dog',
      `${config.host}/public/static/images/animal-a/dog.jpg`,
      `${config.host}/public/static/audio/animal-a/dog.mp3`,
      'Собака',
      'cat0',
      '3',
    ),
    new Card(
      'dolphin',
      'Dolphin',
      `${config.host}/public/static/images/animal-a/dolphin.jpg`,
      `${config.host}/public/static/audio/animal-a/dolphin.mp3`,
      'Дельфин',
      'cat0',
      '4',
    ),
    new Card(
      'fish',
      'Fish',
      `${config.host}/public/static/images/animal-a/fish.jpg`,
      `${config.host}/public/static/audio/animal-a/fish.mp3`,
      'Рыба',
      'cat0',
      '5',
    ),
    new Card(
      'frog',
      'Frog',
      `${config.host}/public/static/images/animal-a/frog.jpg`,
      `${config.host}/public/static/audio/animal-a/frog.mp3`,
      'Лягушка',
      'cat0',
      '6',
    ),
    new Card(
      'giraffe',
      'Giraffe',
      `${config.host}/public/static/images/animal-a/giraffe.jpg`,
      `${config.host}/public/static/audio/animal-a/giraffe.mp3`,
      'Жираф',
      'cat0',
      '7',
    ),
    // Animals set B #1
    new Card(
      'chicken',
      'Chicken',
      `${config.host}/public/static/images/animal-b/chicken.jpg`,
      `${config.host}/public/static/audio/animal-b/chicken.mp3`,
      'Курица',
      'cat1',
      '8',
    ),
    new Card(
      'horse',
      'Horse',
      `${config.host}/public/static/images/animal-b/horse.jpg`,
      `${config.host}/public/static/audio/animal-b/horse.mp3`,
      'Лошадь',
      'cat1',
      '9',
    ),
    new Card(
      'lion',
      'Lion',
      `${config.host}/public/static/images/animal-b/lion.jpg`,
      `${config.host}/public/static/audio/animal-b/lion.mp3`,
      'Лев',
      'cat1',
      '10',
    ),
    new Card(
      'mouse',
      'Mouse',
      `${config.host}/public/static/images/animal-b/mouse.jpg`,
      `${config.host}/public/static/audio/animal-b/mouse.mp3`,
      'Мышь',
      'cat1',
      '11',
    ),
    new Card(
      'pig',
      'pig',
      `${config.host}/public/static/images/animal-b/pig.jpg`,
      `${config.host}/public/static/audio/animal-b/pig.mp3`,
      'Свинья',
      'cat1',
      '12',
    ),
    new Card(
      'rabbit',
      'Rabbit',
      `${config.host}/public/static/images/animal-b/rabbit.jpg`,
      `${config.host}/public/static/audio/animal-b/rabbit.mp3`,
      'Кролик',
      'cat1',
      '13',
    ),
    new Card(
      'sheep',
      'Sheep',
      `${config.host}/public/static/images/animal-b/sheep.jpg`,
      `${config.host}/public/static/audio/animal-b/sheep.mp3`,
      'Овца',
      'cat1',
      '14',
    ),
    new Card(
      'turtle',
      'Turtle',
      `${config.host}/public/static/images/animal-b/turtle.jpg`,
      `${config.host}/public/static/audio/animal-b/turtle.mp3`,
      'Черепаха',
      'cat1',
      '15',
    ),
    // Animals set C #2
    new Card(
      'antelope',
      'Antelope',
      `${config.host}/public/static/images/animal-c/antelope.jpg`,
      `${config.host}/public/static/audio/animal-c/antelope.mp3`,
      'Антилопа',
      'cat2',
      '16',
    ),
    new Card(
      'bear',
      'Bear',
      `${config.host}/public/static/images/animal-c/bear.jpg`,
      `${config.host}/public/static/audio/animal-c/bear.mp3`,
      'Медведь',
      'cat2',
      '17',
    ),
    new Card(
      'buffalo',
      'Buffalo',
      `${config.host}/public/static/images/animal-c/buffalo.jpg`,
      `${config.host}/public/static/audio/animal-c/buffalo.mp3`,
      'Буйвол',
      'cat2',
      '18',
    ),
    new Card(
      'cow',
      'Cow',
      `${config.host}/public/static/images/animal-c/cow.jpg`,
      `${config.host}/public/static/audio/animal-c/cow.mp3`,
      'Корова',
      'cat2',
      '19',
    ),
    new Card(
      'flamingo',
      'Flamingo',
      `${config.host}/public/static/images/animal-c/flamingo.jpg`,
      `${config.host}/public/static/audio/animal-c/flamingo.mp3`,
      'Фламинго',
      'cat2',
      '20',
    ),
    new Card(
      'fox',
      'Fox',
      `${config.host}/public/static/images/animal-c/fox.jpg`,
      `${config.host}/public/static/audio/animal-c/fox.mp3`,
      'Лиса',
      'cat2',
      '21',
    ),
    new Card(
      'hedgehog',
      'Hedgehog',
      `${config.host}/public/static/images/animal-c/hedgehog.jpg`,
      `${config.host}/public/static/audio/animal-c/hedgehog.mp3`,
      'Ёж',
      'cat2',
      '22',
    ),
    new Card(
      'squirrel',
      'Squirrel',
      `${config.host}/public/static/images/animal-c/squirrel.jpg`,
      `${config.host}/public/static/audio/animal-c/squirrel.mp3`,
      'Белка',
      'cat2',
      '23',
    ),
    // Food #3
    new Card(
      'carrot',
      'Carrot',
      `${config.host}/public/static/images/food/carrot.jpg`,
      `${config.host}/public/static/audio/food/carrot.mp3`,
      'Морковь',
      'cat3',
      '24',
    ),
    new Card(
      'donut',
      'Donut',
      `${config.host}/public/static/images/food/donut.jpg`,
      `${config.host}/public/static/audio/food/donut.mp3`,
      'Пончик',
      'cat3',
      '25',
    ),
    new Card(
      'pear',
      'Pear',
      `${config.host}/public/static/images/food/pear.jpg`,
      `${config.host}/public/static/audio/food/pear.mp3`,
      'Груша',
      'cat3',
      '26',
    ),
    new Card(
      'pizza',
      'Pizza',
      `${config.host}/public/static/images/food/pizza.jpg`,
      `${config.host}/public/static/audio/food/pizza.mp3`,
      'Пицца',
      'cat3',
      '27',
    ),
    new Card(
      'radish',
      'Radish',
      `${config.host}/public/static/images/food/radish.jpg`,
      `${config.host}/public/static/audio/food/radish.mp3`,
      'Редис',
      'cat3',
      '28',
    ),
    new Card(
      'strawberry',
      'Strawberry',
      `${config.host}/public/static/images/food/strawberry.jpg`,
      `${config.host}/public/static/audio/food/strawberry.mp3`,
      'Клубника',
      'cat3',
      '29',
    ),
    new Card(
      'tomatoes',
      'Tomatoes',
      `${config.host}/public/static/images/food/tomatoes.jpg`,
      `${config.host}/public/static/audio/food/tomatoes.mp3`,
      'Помидоры',
      'cat3',
      '30',
    ),
    new Card(
      'watermelon',
      'Watermelon',
      `${config.host}/public/static/images/food/watermelon.jpg`,
      `${config.host}/public/static/audio/food/watermelon.mp3`,
      'Арбуз',
      'cat3',
      '31',
    ),
    // Action (set A) #4
    new Card(
      'cry',
      'Cry',
      `${config.host}/public/static/images/action-a/cry.jpg`,
      `${config.host}/public/static/audio/action-a/cry.mp3`,
      'Плакать',
      'cat4',
      '32',
    ),
    new Card(
      'dance',
      'Dance',
      `${config.host}/public/static/images/action-a/dance.jpg`,
      `${config.host}/public/static/audio/action-a/dance.mp3`,
      'Танцевать',
      'cat4',
      '33',
    ),
    new Card(
      'dive',
      'Dive',
      `${config.host}/public/static/images/action-a/dive.jpg`,
      `${config.host}/public/static/audio/action-a/dive.mp3`,
      'Нырять',
      'cat4',
      '34',
    ),
    new Card(
      'draw',
      'Draw',
      `${config.host}/public/static/images/action-a/draw.jpg`,
      `${config.host}/public/static/audio/action-a/draw.mp3`,
      'Рисовать',
      'cat4',
      '35',
    ),
    new Card(
      'fish',
      'Fish',
      `${config.host}/public/static/images/action-a/fish.jpg`,
      `${config.host}/public/static/audio/action-a/fish.mp3`,
      'Ловить рыбу',
      'cat4',
      '36',
    ),
    new Card(
      'hug',
      'Hug',
      `${config.host}/public/static/images/action-a/hug.jpg`,
      `${config.host}/public/static/audio/action-a/hug.mp3`,
      'Обнимать',
      'cat4',
      '37',
    ),
    new Card(
      'jump',
      'Jump',
      `${config.host}/public/static/images/action-a/jump.jpg`,
      `${config.host}/public/static/audio/action-a/jump.mp3`,
      'Прыгать',
      'cat4',
      '38',
    ),
    new Card(
      'open',
      'Open',
      `${config.host}/public/static/images/action-a/open.jpg`,
      `${config.host}/public/static/audio/action-a/open.mp3`,
      'Открывать',
      'cat4',
      '39',
    ),
    // Action (set B) #5
    new Card(
      'fly',
      'Fly',
      `${config.host}/public/static/images/action-b/fly.jpg`,
      `${config.host}/public/static/audio/action-b/fly.mp3`,
      'Летать',
      'cat5',
      '40',
    ),
    new Card(
      'play',
      'Play',
      `${config.host}/public/static/images/action-b/play.jpg`,
      `${config.host}/public/static/audio/action-b/play.mp3`,
      'Играть',
      'cat5',
      '41',
    ),
    new Card(
      'point',
      'Point',
      `${config.host}/public/static/images/action-b/point.jpg`,
      `${config.host}/public/static/audio/action-b/point.mp3`,
      'Указывать',
      'cat5',
      '42',
    ),
    new Card(
      'ride',
      'Ride',
      `${config.host}/public/static/images/action-b/ride.jpg`,
      `${config.host}/public/static/audio/action-b/ride.mp3`,
      'Ездить',
      'cat5',
      '43',
    ),
    new Card(
      'run',
      'Run',
      `${config.host}/public/static/images/action-b/run.jpg`,
      `${config.host}/public/static/audio/action-b/run.mp3`,
      'Бегать',
      'cat5',
      '44',
    ),
    new Card(
      'skip',
      'Skip',
      `${config.host}/public/static/images/action-b/skip.jpg`,
      `${config.host}/public/static/audio/action-b/skip.mp3`,
      'Пропускать, прыгать',
      'cat5',
      '45',
    ),
    new Card(
      'sing',
      'Sing',
      `${config.host}/public/static/images/action-b/sing.jpg`,
      `${config.host}/public/static/audio/action-b/sing.mp3`,
      'Петь',
      'cat5',
      '46',
    ),
    new Card(
      'swim',
      'Swim',
      `${config.host}/public/static/images/action-b/swim.jpg`,
      `${config.host}/public/static/audio/action-b/swim.mp3`,
      'Плавать',
      'cat5',
      '47',
    ),
    // Clothes #6
    new Card(
      'blouse',
      'Blouse',
      `${config.host}/public/static/images/clothes/blouse.jpg`,
      `${config.host}/public/static/audio/clothes/blouse.mp3`,
      'Блузка',
      'cat6',
      '48',
    ),
    new Card(
      'boot',
      'Boot',
      `${config.host}/public/static/images/clothes/boot.jpg`,
      `${config.host}/public/static/audio/clothes/boot.mp3`,
      'Ботинок',
      'cat6',
      '49',
    ),
    new Card(
      'coat',
      'Coat',
      `${config.host}/public/static/images/clothes/coat.jpg`,
      `${config.host}/public/static/audio/clothes/coat.mp3`,
      'Пальто',
      'cat6',
      '50',
    ),
    new Card(
      'dress',
      'Dress',
      `${config.host}/public/static/images/clothes/dress.jpg`,
      `${config.host}/public/static/audio/clothes/dress.mp3`,
      'Платье',
      'cat6',
      '51',
    ),
    new Card(
      'pants',
      'Pants',
      `${config.host}/public/static/images/clothes/pants.jpg`,
      `${config.host}/public/static/audio/clothes/pants.mp3`,
      'Брюки',
      'cat6',
      '52',
    ),
    new Card(
      'shirt',
      'Shirt',
      `${config.host}/public/static/images/clothes/shirt.jpg`,
      `${config.host}/public/static/audio/clothes/shirt.mp3`,
      'Рубашка',
      'cat6',
      '53',
    ),
    new Card(
      'shoe',
      'Shoe',
      `${config.host}/public/static/images/clothes/shoe.jpg`,
      `${config.host}/public/static/audio/clothes/shoe.mp3`,
      'Туфли',
      'cat6',
      '54',
    ),
    new Card(
      'skirt',
      'Skirt',
      `${config.host}/public/static/images/clothes/skirt.jpg`,
      `${config.host}/public/static/audio/clothes/skirt.mp3`,
      'Юбка',
      'cat6',
      '55',
    ),
    // Emotions #7
    new Card(
      'angry',
      'Angry',
      `${config.host}/public/static/images/emotions/angry.jpg`,
      `${config.host}/public/static/audio/emotions/angry.mp3`,
      'Сердитый',
      'cat7',
      '56',
    ),
    new Card(
      'happy',
      'Happy',
      `${config.host}/public/static/images/emotions/happy.jpg`,
      `${config.host}/public/static/audio/emotions/happy.mp3`,
      'Счастливый',
      'cat7',
      '57',
    ),
    new Card(
      'laugh',
      'Laugh',
      `${config.host}/public/static/images/emotions/laugh.jpg`,
      `${config.host}/public/static/audio/emotions/laugh.mp3`,
      'Смех',
      'cat7',
      '58',
    ),
    new Card(
      'sad',
      'Sad',
      `${config.host}/public/static/images/emotions/sad.jpg`,
      `${config.host}/public/static/audio/emotions/sad.mp3`,
      'Грустный',
      'cat7',
      '59',
    ),
    new Card(
      'scared',
      'Scared',
      `${config.host}/public/static/images/emotions/scared.jpg`,
      `${config.host}/public/static/audio/emotions/scared.mp3`,
      'Испуганный',
      'cat7',
      '60',
    ),
    new Card(
      'smile',
      'Smile',
      `${config.host}/public/static/images/emotions/smile.jpg`,
      `${config.host}/public/static/audio/emotions/smile.mp3`,
      'Улыбка',
      'cat7',
      '61',
    ),
    new Card(
      'surprised',
      'Surprised',
      `${config.host}/public/static/images/emotions/surprised.jpg`,
      `${config.host}/public/static/audio/emotions/surprised.mp3`,
      'Удивлённый',
      'cat7',
      '62',
    ),
    new Card(
      'tired',
      'Tired',
      `${config.host}/public/static/images/emotions/tired.jpg`,
      `${config.host}/public/static/audio/emotions/tired.mp3`,
      'Уставший',
      'cat7',
      '63',
    ),
  ];

  async create(createCardDto: CreateCardDto, categoryId: string): Promise<Card> {
    const { name, title, image, audio, translation } = createCardDto;
    const card = new Card(name, title, image, audio, translation, categoryId);
    this.cards.push(card);
    return card;
  }

  async get(id: string): Promise<Card | null> {
    return this.cards.find(card => card.id === id) ?? null;
  }

  async getByCategory(id: string): Promise<Card[]> {
    return this.cards.filter(card => card.categoryId === id);
  }

  async update(id: string, card: Partial<CreateCardDto>): Promise<Card | null> {
    const index = this.cards.findIndex(card => card.id === id);

    if (index === -1) {
      return null;
    }

    const updatedCard = this.cards[index].update(card);
    this.cards[index] = updatedCard;
    return updatedCard;
  }

  async remove(id: string): Promise<Card | null> {
    const index = this.cards.findIndex(card => card.id === id);

    if (index === -1) {
      return null;
    }

    const cardToRemove = this.cards[index];
    this.cards.splice(index, 1);
    return cardToRemove;
  }

  async removeByCategory(id: string): Promise<Card[]> {
    const removedCards: Card[] = this.cards.filter(card => card.id === id);
    this.cards = this.cards.filter(card => card.id !== id);
    return removedCards;
  }
}
